### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by DarrienG** [sivssdn/whac_a_mole#3]
I'd like to be able to view the code and use it in my own repos, but there's no license so legally I can't :(

Popular licenses are:
* [GNU GPL v3](https://www.gnu.org/licenses/gpl-3.0.txt)
* [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0.txt)
* [MIT](https://mit-license.org/)

**Comment by sivssdn** [comment]
Thanks mate, added MIT license. Links are helpful.
Please feel free to use as you like :)
